# ARG ELK_VERSION

# https://github.com/elastic/elasticsearch-docker
# FROM docker.elastic.co/elasticsearch/elasticsearch:5.5.0
FROM liaodashuai/elasticsearch:1.0.2
# Add your elasticsearch plugins setup here
# Example: RUN elasticsearch-plugin install analysis-icu
#RUN apt-get update && apt-get install zip
#RUN mkdir -p /usr/share/elasticsearch/plugins/ik
#RUN cd /usr/share/elasticsearch/plugins/ik && wget https://github.com/medcl/elasticsearch-analysis-ik/releases/download/v5.5.0/elasticsearch-analysis-ik-5.5.0.zip && unzip elasticsearch-analysis-ik-5.5.0.zip
